app:
  name: diagnos
  log_level: info

targets:
  remote-vm-1:
    host: ssh.quickorder.in
    user: ubuntu

  remote-vm-2:
    host: 192.168.252.4
    user: ubuntu

telemetry:
  prometheus:
    url: http://192.168.252.3:9090
    auth:
      type: none

ai:
  model: gemini/gemini-3.5-flash-lite

  models:
    gemini/gemini-3.5-flash-lite:
      base_url: https://generativelanguage.googleapis.com
      api_key_env: GEMINI_API_KEY

  request_limits:
    max_lines_context_file: 1000

logs:
  applications:
    - name: quickorder
      service: quickorder
      paths:
        - /home/ubuntu/.pm2/logs/quickorder-error.log
        - /home/ubuntu/.pm2/logs/quickorder-out.log